
// The countries list is generated by AI. If there's a mistake, open an issue or pull request with correct info.

pub(crate) fn get_country(city_in: &str) -> std::io::Result<String>
{
    let tz_cities_countries: Vec<(&str, &str)> = vec![
        // Africa
        ("Algiers", "Algeria"),
        ("Luanda", "Angola"),
        ("Cotonou", "Benin"),
        ("Gaborone", "Botswana"),
        ("Ouagadougou", "Burkina Faso"),
        ("Bujumbura", "Burundi"),
        ("Yaoundé", "Cameroon"),
        ("Praia", "Cape Verde"),
        ("Bangui", "Central African Republic"),
        ("N'Djamena", "Chad"),
        ("Moroni", "Comoros"),
        ("Kinshasa", "DR Congo"), // West
        ("Lubumbashi", "DR Congo"), // East
        ("Brazzaville", "Congo"),
        ("Yamoussoukro", "Côte d'Ivoire"),
        ("Djibouti City", "Djibouti"),
        ("Cairo", "Egypt"),
        ("Malabo", "Equatorial Guinea"),
        ("Asmara", "Eritrea"),
        ("Mbabane", "Eswatini"),
        ("Addis Ababa", "Ethiopia"),
        ("Libreville", "Gabon"),
        ("Banjul", "Gambia"),
        ("Accra", "Ghana"),
        ("Conakry", "Guinea"),
        ("Bissau", "Guinea-Bissau"),
        ("Nairobi", "Kenya"),
        ("Maseru", "Lesotho"),
        ("Monrovia", "Liberia"),
        ("Tripoli", "Libya"),
        ("Antananarivo", "Madagascar"),
        ("Lilongwe", "Malawi"),
        ("Bamako", "Mali"),
        ("Nouakchott", "Mauritania"),
        ("Port Louis", "Mauritius"),
        ("Rabat", "Morocco"),
        ("Maputo", "Mozambique"),
        ("Windhoek", "Namibia"),
        ("Niamey", "Niger"),
        ("Lagos", "Nigeria"),
        ("Kigali", "Rwanda"),
        ("São Tomé", "São Tomé and Príncipe"),
        ("Dakar", "Senegal"),
        ("Victoria", "Seychelles"),
        ("Freetown", "Sierra Leone"),
        ("Mogadishu", "Somalia"),
        ("Pretoria", "South Africa"),
        ("Juba", "South Sudan"),
        ("Khartoum", "Sudan"),
        ("Dodoma", "Tanzania"),
        ("Lomé", "Togo"),
        ("Tunis", "Tunisia"),
        ("Kampala", "Uganda"),
        ("Lusaka", "Zambia"),
        ("Harare", "Zimbabwe"),

        // Americas
        ("Buenos Aires", "Argentina"),
        ("Nassau", "Bahamas"),
        ("Bridgetown", "Barbados"),
        ("Belmopan", "Belize"),
        ("La Paz", "Bolivia"),
        ("Brasília", "Brazil"),
        ("Ottawa", "Canada"), // East Coast
        ("Winnipeg", "Canada"), // Central
        ("Edmonton", "Canada"), // Mountain
        ("Vancouver", "Canada"), // Pacific
        ("Santiago", "Chile"),
        ("Bogotá", "Colombia"),
        ("San José", "Costa Rica"),
        ("Havana", "Cuba"),
        ("Roseau", "Dominica"),
        ("Santo Domingo", "Dominican Republic"),
        ("Quito", "Ecuador"),
        ("San Salvador", "El Salvador"),
        ("Saint George's", "Grenada"),
        ("Guatemala City", "Guatemala"),
        ("Georgetown", "Guyana"),
        ("Port-au-Prince", "Haiti"),
        ("Tegucigalpa", "Honduras"),
        ("Kingston", "Jamaica"),
        ("Mexico City", "Mexico"),
        ("Managua", "Nicaragua"),
        ("Panama City", "Panama"),
        ("Asunción", "Paraguay"),
        ("Lima", "Peru"),
        ("Basseterre", "Saint Kitts and Nevis"),
        ("Castries", "Saint Lucia"),
        ("Kingstown", "Saint Vincent and the Grenadines"),
        ("Paramaribo", "Suriname"),
        ("Port of Spain", "Trinidad and Tobago"),
        ("Washington, D.C.", "United States"), // Eastern
        ("Chicago", "United States"), // Central
        ("Denver", "United States"), // Mountain
        ("Los Angeles", "United States"), // Pacific
        ("Anchorage", "United States"), // Alaska
        ("Honolulu", "United States"), // Hawaii
        ("Montevideo", "Uruguay"),
        ("Caracas", "Venezuela"),

        // Asia
        ("Kabul", "Afghanistan"),
        ("Yerevan", "Armenia"),
        ("Baku", "Azerbaijan"),
        ("Manama", "Bahrain"),
        ("Dhaka", "Bangladesh"),
        ("Thimphu", "Bhutan"),
        ("Bandar Seri Begawan", "Brunei"),
        ("Phnom Penh", "Cambodia"),
        ("Beijing", "China"),
        ("Nicosia", "Cyprus"),
        ("Dili", "East Timor"),
        ("Tbilisi", "Georgia"),
        ("New Delhi", "India"),
        ("Jakarta", "Indonesia"), // Western
        ("Makassar", "Indonesia"), // Central
        ("Jayapura", "Indonesia"), // Eastern
        ("Tehran", "Iran"),
        ("Baghdad", "Iraq"),
        ("Jerusalem", "Israel"),
        ("Tokyo", "Japan"),
        ("Amman", "Jordan"),
        ("Nur-Sultan", "Kazakhstan"), // Western
        ("Almaty", "Kazakhstan"), // Eastern
        ("Kuwait City", "Kuwait"),
        ("Bishkek", "Kyrgyzstan"),
        ("Vientiane", "Laos"),
        ("Beirut", "Lebanon"),
        ("Kuala Lumpur", "Malaysia"),
        ("Malé", "Maldives"),
        ("Ulaanbaatar", "Mongolia"),
        ("Naypyidaw", "Myanmar"),
        ("Kathmandu", "Nepal"),
        ("Pyongyang", "North Korea"),
        ("Muscat", "Oman"),
        ("Karachi", "Pakistan"),
        ("Ramallah", "Palestine"),
        ("Manila", "Philippines"),
        ("Doha", "Qatar"),
        ("Riyadh", "Saudi Arabia"),
        ("Singapore", "Singapore"),
        ("Seoul", "South Korea"),
        ("Colombo", "Sri Lanka"),
        ("Damascus", "Syria"),
        ("Taipei", "Taiwan"),
        ("Dushanbe", "Tajikistan"),
        ("Bangkok", "Thailand"),
        ("Ankara", "Turkey"),
        ("Ashgabat", "Turkmenistan"),
        ("Abu Dhabi", "United Arab Emirates"),
        ("Tashkent", "Uzbekistan"),
        ("Hanoi", "Vietnam"),
        ("Sana'a", "Yemen"),

        // Europe
        ("Tirana", "Albania"),
        ("Andorra la Vella", "Andorra"),
        ("Vienna", "Austria"),
        ("Minsk", "Belarus"),
        ("Brussels", "Belgium"),
        ("Sarajevo", "Bosnia and Herzegovina"),
        ("Sofia", "Bulgaria"),
        ("Zagreb", "Croatia"),
        ("Prague", "Czech Republic"),
        ("Copenhagen", "Denmark"),
        ("Tallinn", "Estonia"),
        ("Helsinki", "Finland"),
        ("Paris", "France"),
        ("Berlin", "Germany"),
        ("Gibraltar", "Gibraltar"),
        ("Athens", "Greece"),
        ("Budapest", "Hungary"),
        ("Reykjavik", "Iceland"),
        ("Dublin", "Ireland"),
        ("Rome", "Italy"),
        ("Pristina", "Kosovo"),
        ("Riga", "Latvia"),
        ("Vaduz", "Liechtenstein"),
        ("Vilnius", "Lithuania"),
        ("Luxembourg City", "Luxembourg"),
        ("Valletta", "Malta"),
        ("Chișinău", "Moldova"),
        ("Monaco", "Monaco"),
        ("Podgorica", "Montenegro"),
        ("Amsterdam", "Netherlands"),
        ("Skopje", "North Macedonia"),
        ("Oslo", "Norway"),
        ("Warsaw", "Poland"),
        ("Lisbon", "Portugal"),
        ("Bucharest", "Romania"),
        ("Moscow", "Russia"), // Western
        ("Novosibirsk", "Russia"), // Central
        ("Vladivostok", "Russia"), // Far East
        ("San Marino", "San Marino"),
        ("Belgrade", "Serbia"),
        ("Bratislava", "Slovakia"),
        ("Ljubljana", "Slovenia"),
        ("Madrid", "Spain"),
        ("Stockholm", "Sweden"),
        ("Bern", "Switzerland"),
        ("Kyiv", "Ukraine"),
        ("London", "United Kingdom"),
        ("Vatican City", "Vatican City"),

        // Oceania
        ("Canberra", "Australia"), // Eastern
        ("Darwin", "Australia"), // Central
        ("Perth", "Australia"), // Western
        ("Suva", "Fiji"),
        ("Tarawa", "Kiribati"),
        ("Majuro", "Marshall Islands"),
        ("Palikir", "Micronesia"),
        ("Yaren", "Nauru"),
        ("Wellington", "New Zealand"),
        ("Ngerulmud", "Palau"),
        ("Port Moresby", "Papua New Guinea"),
        ("Apia", "Samoa"),
        ("Honiara", "Solomon Islands"),
        ("Nukuʻalofa", "Tonga"),
        ("Funafuti", "Tuvalu"),
        ("Port Vila", "Vanuatu"),
    ];

    for (city, country) in tz_cities_countries {
        if city_in == city {
            return Ok(String::from(country));
        }
    }

    Ok(String::new())
}
